# Numpy Cheat Sheet

The NumPy library is the core library for scientific computing in
Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays.

http://www.numpy.org/

In [1]:
import numpy as np

### Creating Arrays

In [2]:
# 1D array
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
# 2D array
b = np.array([(1.6, 2.6, 2.7), (2.6, 6.3, 8.3)], dtype = float)
b

array([[ 1.6,  2.6,  2.7],
       [ 2.6,  6.3,  8.3]])

In [11]:
# 3D array
c = np.array([[(1.2, 3, 5.3), (8.4, 4, 2.3)], [(2.2, 4, 1), (2, 3, 1)]], dtype = float)
c

array([[[ 1.2,  3. ,  5.3],
        [ 8.4,  4. ,  2.3]],

       [[ 2.2,  4. ,  1. ],
        [ 2. ,  3. ,  1. ]]])

### Initial Placeholders

In [13]:
# Create an array of zeros
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [14]:
# Create an array of ones
np.ones((2, 3, 5), dtype = np.int16)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [17]:
# Docstring: arange([start,] stop[, step,], dtype=None)
# Create an array of evenly spaced values (step value)
d = np.arange(10, 100, 2)
d

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [20]:
# Return evenly spaced numbers over a specified interval.
np.linspace(0, 2 ,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [27]:
# Create a constant array
e = np.full((2, 3, 4), 7)
e

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [31]:
# Create a 2X2 identity matrix
imtx = np.eye(5)
imtx

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [36]:
# Create an array with random values
# Return random floats in the half-open interval [0.0, 1.0).
np.random.random((3, 4))

array([[ 0.82540099,  0.05187347,  0.31739792,  0.79270445],
       [ 0.84692529,  0.40508938,  0.47042914,  0.20967575],
       [ 0.67825554,  0.53915446,  0.54678728,  0.1079064 ]])

In [43]:
# Create an empty array
empty = np.empty((3, 3))
empty

array([[ 0.39491504,  0.78207874,  0.30319203],
       [ 0.55820864,  0.03460134,  0.12888468],
       [ 0.48374664,  0.49017932,  0.37729622]])

## I/O

### Saving & Loading On Disk

In [51]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([(6, 6, 5), (1, 4, 2)])

In [52]:
# Save an array to a binary file in NumPy ``.npy`` format.
np.save('my_array', a)

In [53]:
# Load arrays or pickled objects from ``.npy``, ``.npz`` or pickled files.
np.load('my_array.npy')

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
# Save several arrays into a single file in uncompressed ``.npz`` format.
np.savez('array_gorup.npz', a, b)

In [84]:
data = np.load('array_gorup.npz')
for k in data:
    print(data[k])

[[1 2 3]
 [4 5 6]]
[[6 6 5]
 [1 4 2]]


### Saving & Loading Text Files

In [95]:
# Load data from a text file.
np.loadtxt('test.txt')

/Users/Carl/work/python_env/p3-uruz7/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: loadtxt: Empty input file: "test.txt"
  


array([], dtype=float64)

In [94]:
# Load data from a text file, with missing values handled as specified.
np.genfromtxt('my_file.csv', delimiter = ',')

/Users/Carl/work/python_env/p3-uruz7/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: genfromtxt: Empty input file: "my_file.csv"
  


array([], dtype=float64)

In [110]:
text_array = np.array(['Ruru', 'MaoMao'], dtype = np.str)
np.savetxt('array_to_txt.txt', text_array, delimiter = ' ', fmt = "%s")

In [113]:
read_array = np.loadtxt('array_to_txt.txt', dtype = str)
read_array

array(['Ruru', 'MaoMao'],
      dtype='<U6')

## Data Types

In [118]:
# Signed 64-bit integer types
np.int64

numpy.int64

In [120]:
# Standard double-precision floating point
np.float32

numpy.float32

In [121]:
# Complex numbers represented by 128 floats
np.complex

complex

In [123]:
# Boolean type storing TRUE and FALSE values
np.bool

bool

In [124]:
# Python object type
np.object

object

In [125]:
# Fixed-length string type
np.string_

numpy.bytes_

In [126]:
# Fixed-length unicode type
np.unicode_

numpy.str_