# Machine Learning with Python

We will be using the Scikit Learn package.

It's the most popular machine learning package for Python and has a lot of algrithms built-in.

Every algorithm is exposed in scikit-learn via an "Estimator".
First you'll import the model, the general form is:

** from sklearn.family import Model **

For example:

In [3]:
# Family: linear_model
# Model: LinearRegression, this is the estimator object and also the model itself.
from sklearn.linear_model import LinearRegression

### Estimator parameters

All the parameters of an estimator can be set when it is instantiated, and have suitable default values.

For example:

In [4]:
model = LinearRegression(normalize = True)
print(model)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)


Once you have your model created with your parameters, it is time to fit your model on some data.
But remember, we should split this data into a training set and a test set.

In [5]:
import numpy as np
from sklearn.cross_validation import train_test_split

In [7]:
X, y = np.arange(10).reshape((5, 2)), range(5)

In [8]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [10]:
list(y)

[0, 1, 2, 3, 4]

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [12]:
X_train

array([[8, 9],
       [6, 7],
       [4, 5]])

In [13]:
y_train

[4, 3, 2]

In [14]:
X_test

array([[2, 3],
       [0, 1]])

In [15]:
y_test

[1, 0]

Now that we have split the data, we can train/fit our model on the training data.

This is done through the model.fit() method:
**model.fit(X_train, y_train)**

Now the model has been fit and trained on the training data.

The model is ready to predict labels or values on the test set.

We get predicted values using the predict method: **predictions = model.predict(X_test)**

We can then evaluate our model by comparing our predictions to the correct values.

The evaluation method depends on what sort of machine learning algorithm we are using (e.g. Regression, Classification, Clustering, etc.)