# Tensorflow with ContribLearn

As we saw previously how to build a full Multi-Layer Perceptron model with full Sessions in Tensorflow. Unfortunately this was an extremely involved process. However developers have created ContribLearn (previously known as TKFlow or SciKit-Flow) which provides a SciKit Learn like interface for Tensorflow.

It is much easier to use, but you sacrifice some level of customization of your model. Let's go ahead and explore it.

## Get the Data

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
X = iris['data']

In [4]:
y = iris['target']

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
y.dtype

dtype('int64')

## Train Test Split

In [8]:
from sklearn.cross_validation import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Contrib.learn

In [40]:
import numpy as np
X_train = np.array( X_train, dtype=np.float32 ) 
X_test = np.array( X_test, dtype=np.float32 )

In [41]:
from tensorflow.contrib.learn.python import learn

In [42]:
feature_columns = learn.infer_real_valued_columns_from_input(X_train)

In [43]:
classifier = learn.DNNClassifier(hidden_units=[10,20,10], n_classes=3, feature_columns=feature_columns)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x119c42c18>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/var/folders/m1/bt6j8jfd0yn_t0nzdjxcldhm0000gn/T/tmpjjugtzej'}


In [44]:

import tensorflow as tf 
def get_train_inputs():
    x = tf.constant(X_train)
    y = tf.constant(y_train)

    return x, y

classifier.fit(input_fn=get_train_inputs, steps=200)

Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/m1/bt6j8jfd0yn_t0nzdjxcldhm0000gn/T/tmpjjugtzej/model.ckpt.
INFO:tensorflow:loss = 1.72814, step = 1
INFO:tensorflow:global_step/sec: 966.781
INFO:tensorflow:loss = 0.341727, step = 101 (0.104 sec)
INFO:tensorflow:Saving checkpoints for 200 into /var/folders/m1/bt6j8jfd0yn_t0nzdjxcldhm0000gn/T/tmpjjugtzej/model.ckpt.
INFO:tensorflow:Loss for final step: 0.0855629.


DNNClassifier(params={'head': <tensorflow.contrib.learn.python.learn.estimators.head._MultiClassHead object at 0x119c42518>, 'hidden_units': [10, 20, 10], 'feature_columns': (_RealValuedColumn(column_name='', dimension=4, default_value=None, dtype=tf.float32, normalizer=None),), 'optimizer': None, 'activation_fn': <function relu at 0x10f33a9d8>, 'dropout': None, 'gradient_clip_norm': None, 'embedding_lr_multipliers': None, 'input_layer_min_slice_size': None})

In [45]:
def get_test_inputs():
    x = tf.constant(X_test)
    return x 

iris_predictions = list(classifier.predict_classes (input_fn=get_test_inputs))

INFO:tensorflow:Restoring parameters from /var/folders/m1/bt6j8jfd0yn_t0nzdjxcldhm0000gn/T/tmpjjugtzej/model.ckpt-200


In [46]:
from sklearn.metrics import classification_report, confusion_matrix

In [47]:
print(classification_report(y_test,  iris_predictions))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       1.00      0.89      0.94        18
          2       0.87      1.00      0.93        13

avg / total       0.96      0.96      0.96        45



In [48]:
print(confusion_matrix(y_test,  iris_predictions))

[[14  0  0]
 [ 0 16  2]
 [ 0  0 13]]
